export const ActionTypes = {
    // LIKE_SONG: "LIKE_SONG",
    // UNLIKE_SONG: "UNLIKE_SONG",
    // PLAY_SONG: "PLAY_SONG",
    // PAUSE_SONG: "PAUSE_SONG"
    TOGGLE_PLAY_PAUSE: "TOGGLE_PLAY_PAUSE",
    TOGGLE_LIKE_UNLIKE: "TOGGLE_LIKE_UNLIKE"
}