export const postActionTypes = {
    FETCH_POSTS: "FETCH_POSTS",
    FETCH_POSTS_PENDING: "FETCH_POSTS_PENDING",
    FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
    FETCH_POSTS_ERROR: "FETCH_POSTS_ERROR",
    CREATE_POST: "CREATE_POST",
    CREATE_POST_PENDING: "CREATE_POST_PENDING",
    CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
    CREATE_POST_ERROR: "CREATE_POST_ERROR"
}